# Config file for automatic testing at travis-ci.com
branches:
  only:
  - main

language: python
python:
  - 3.8
#  - 3.7
#  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install: pip install -U tox-travis
install: pip install -U -r requirements_dev.txt

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: felipeangelimvieira
  password: env(pypi_token)
  on:
    branch: main
    tags: true
    repo: felipeangelim/shared_nearest_neighbors
    python: 3.8
